import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from 'components/Header';
import SideMenu from 'components/SideMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex h-[calc(100vh-38px)]">
          <SideMenu />
          <main className="flex-grow overflow-y-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
